import { open_sans } from '@/app/fonts'
import { SessionProvider } from 'next-auth/react'
import type { Metadata } from 'next'
import '@/styles/global.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SessionProvider>
      <html lang="en-US" className={open_sans.variable}>
        <body>{children}</body>
      </html>
    </SessionProvider>
  )
}
